from pipeline.basepipeline import BaseCropPipeline,BaseComposePipeline,BaseCaptionPipeline
from pipeline.Florence import FlorenceCaptionPipeline,FlorenceCropPipeline,FlorencePipeline
from pipeline.customcompose import CustomComposePipeline